# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "&#304;hsan Kahveci"                                # Your name
  description: "Ihsan is a sciencist, but a social scientist"   # A brief slogan (optional)
  image: img/headshot.png
  google-analytics: "G-EY73WGB4TP"
  
  #favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    #logo: /img/headshot_square.png
    
    # your sub-pages
    left:
      # - text: "Projects"
      #   href: projects/index.qmd
      # - text: "Teaching"
      #   href: teaching/index.qmd
      # - text: "Publications"
      #   href: publications/index.qmd
      - text: "CV"
        href: cv/index.qmd
    
    # your social media handles
    right:
    - icon: envelope
      href: "mailto:ikahveci@uw.edu"  
    - text: "<i class='fa fa-brands fa-bluesky'></i></a>"
      href: https://bsky.app/profile/ihsankahveci.bsky.social
    - icon: github
      href: https://github.com/ihsankahveci
    - icon: linkedin
      href: https://www.linkedin.com/in/ihsankahveci/

  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Ihsan Kahveci</span>
      <span class="faux-block">All content licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>      
    center: |
      <span class="faux-block">{{< fa brands orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
      <span class="faux-block">{{< fa location-dot >}} {{< var address >}} </span>
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub]({{< var github-url >}})</span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - sandstone 
      - html/sandstone.scss
      #- darkly
      #- solar
      #- html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true