on:
  push:
    branches: main

name: Render and Deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up video redirect
        run: |
          YOUTUBE_URL="${{ secrets.YOUTUBE_URL }}"
          cat > video/index.html <<EOF
          <!DOCTYPE html>
          <html>
            <head>
              <meta name="robots" content="noindex">
              <meta http-equiv="refresh" content="0; url='${YOUTUBE_URL}'">
              <title>Redirecting...</title>
            </head>
            <body>
              <p>If you are not redirected, <a href="${YOUTUBE_URL}">click here</a>.</p>
            </body>
          </html>
          EOF

      - name: Render website
        run: quarto render

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
